version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 3000:3000
      
  server:
    build: ./server
    ports:
      - 5000:8080
    environment:
      DB_URL: mongodb://db/vidly

